---
global:
  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: bah12ocp
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account:  walidshaari
    username: walidshaari
    email: walid.shaari+abc@gmail.com
    dev_revision: main

  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: abc_corp
      email: walid.shaari+abc@gmail.com
    repo: example
  opp: false

main:
  clusterGroupName: hub
