apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: {{ .Values.cloudProvider.storageClass }}-vp
{{- if eq .Values.cloudProvider.storageClass "standard" }}
parameters:
  replication-type: none
  type: pd-standard
provisioner: {{ .Values.cloudProvider.provisioner }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- else if eq .Values.cloudProvider.storageClass "managed-premium" }}
parameters: 
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: {{ .Values.cloudProvider.provisioner }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- else }}
parameters:
  encrypted: "true"
  type: {{ .Values.cloudProvider.storageClass }}
provisioner: {{ .Values.cloudProvider.provisioner }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
{{- end }}
